# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-30 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DFJJ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('programText', models.TextField()),
                ('minPay', models.IntegerField()),
                ('payBack', models.FloatField()),
                ('payDay', models.IntegerField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '项目名称',
                'verbose_name_plural': '项目名称',
                'ordering': ['c_time'],
            },
        ),
    ]
