# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-30 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DFJJ', '0002_programinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
