# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-30 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DFJJ', '0003_auto_20190630_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programinfo',
            options={'ordering': ['ProgramInfo_c_time'], 'verbose_name': '项目名称', 'verbose_name_plural': '项目名称'},
        ),
        migrations.RenameField(
            model_name='programinfo',
            old_name='c_time',
            new_name='ProgramInfo_c_time',
        ),
        migrations.RenameField(
            model_name='programinfo',
            old_name='minPay',
            new_name='ProgramInfo_minPay',
        ),
        migrations.RenameField(
            model_name='programinfo',
            old_name='name',
            new_name='ProgramInfo_name',
        ),
        migrations.RenameField(
            model_name='programinfo',
            old_name='payBack',
            new_name='ProgramInfo_payBack',
        ),
        migrations.RenameField(
            model_name='programinfo',
            old_name='payDay',
            new_name='ProgramInfo_payDay',
        ),
        migrations.RenameField(
            model_name='programinfo',
            old_name='programText',
            new_name='ProgramInfo_programText',
        ),
    ]
