# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-30 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DFJJ', '0005_auto_20190630_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatinginfo',
            options={'ordering': ['c_time'], 'verbose_name': '变更记录', 'verbose_name_plural': '变更记录'},
        ),
        migrations.AlterModelOptions(
            name='programinfo',
            options={'ordering': ['c_time'], 'verbose_name': '项目', 'verbose_name_plural': '项目名称'},
        ),
        migrations.AddField(
            model_name='operatinginfo',
            name='c_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='operatinginfo',
            name='mone_done',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='operatinginfo',
            name='money',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='operatinginfo',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='operatinginfo',
            name='out_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='operatinginfo',
            name='program_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatinginfo',
            name='program_minPay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatinginfo',
            name='program_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='operatinginfo',
            name='program_payBack',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
