# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-30 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DFJJ', '0006_auto_20190630_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinginfo',
            name='c_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='发生时间'),
        ),
        migrations.AlterField(
            model_name='operatinginfo',
            name='mone_done',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='变动之后余额'),
        ),
        migrations.AlterField(
            model_name='operatinginfo',
            name='money',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='变动之前余额'),
        ),
        migrations.AlterField(
            model_name='operatinginfo',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='operatinginfo',
            name='out_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='获得利息时间'),
        ),
        migrations.AlterField(
            model_name='operatinginfo',
            name='program_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='买入数量'),
        ),
        migrations.AlterField(
            model_name='operatinginfo',
            name='program_minPay',
            field=models.IntegerField(blank=True, null=True, verbose_name='最小买入值'),
        ),
        migrations.AlterField(
            model_name='operatinginfo',
            name='program_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='operatinginfo',
            name='program_payBack',
            field=models.FloatField(blank=True, null=True, verbose_name='利率%'),
        ),
        migrations.AlterField(
            model_name='programinfo',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='买入时间'),
        ),
        migrations.AlterField(
            model_name='programinfo',
            name='minPay',
            field=models.IntegerField(verbose_name='最小买入值'),
        ),
        migrations.AlterField(
            model_name='programinfo',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='programinfo',
            name='payBack',
            field=models.FloatField(verbose_name='利率%'),
        ),
        migrations.AlterField(
            model_name='programinfo',
            name='payDay',
            field=models.IntegerField(verbose_name='周期（天）'),
        ),
        migrations.AlterField(
            model_name='programinfo',
            name='programText',
            field=models.TextField(verbose_name='项目简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.FloatField(default=0, verbose_name='用户余额'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
    ]
