# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-30 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DFJJ', '0007_auto_20190630_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinginfo',
            name='c_time',
            field=models.DateField(auto_now=True, null=True, verbose_name='发生时间'),
        ),
        migrations.AlterField(
            model_name='operatinginfo',
            name='out_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='获得利息时间'),
        ),
    ]
