# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-30 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DFJJ', '0008_auto_20190630_2309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperatingInfo',
        ),
    ]
