# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-30 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DFJJ', '0010_operatinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinginfo',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='获得利息时间'),
        ),
    ]
