# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-01 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DFJJ', '0012_auto_20190701_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='realName',
            field=models.CharField(default='', max_length=128, verbose_name='真实姓名'),
        ),
    ]
