# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-03 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DFJJ', '0015_auto_20190703_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatinginfo',
            name='payDay',
            field=models.IntegerField(blank=True, null=True, verbose_name='周期（天）'),
        ),
    ]
