# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-05 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DFJJ', '0016_operatinginfo_payday'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatinginfo',
            name='payMoney',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='应该获得的利润'),
        ),
    ]
